name: Create Nuget package

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkouting code...
      uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Determine version
      run: echo "::set-env name=VERSION::$(git describe --tags --dirty)"

    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release -p:Version=$VERSION

    - name: Preparing nuget source
      run: dotnet nuget add source --username SkyCD --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SkyCD/index.json"

    - name: Publish to GitHub packages 
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
